name = "gmslocker-site"
compatibility_date = "2024-11-01"
workers_dev = true

[assets]
directory = "."
not_found_handling = "single-page-application"

[observability]
enabled = true
head_sampling_rate = 1

[[routes]]
pattern = "gmslocker.com"
custom_domain = true
