/** GMS Locker analysis engine. Missing data remains null; open spots are not weaknesses. */
export class GMSAnalysisEngine {
  constructor(leagueRules = {}) {
    this.starters = leagueRules.starters || [
      { slot:"QB",count:1,accept:["QB"]},{slot:"SFX",count:1,accept:["QB","RB","WR","TE"]},
      { slot:"RB",count:2,accept:["RB"]},{slot:"WR",count:3,accept:["WR"]},{slot:"TE",count:1,accept:["TE"]},
      { slot:"RWT",count:1,accept:["RB","WR","TE"]},{slot:"DL",count:3,accept:["DL"]},
      { slot:"LB",count:2,accept:["LB"]},{slot:"DB",count:3,accept:["DB"]},{slot:"ID",count:2,accept:["DL","LB","DB"]}
    ];
    this.cap = leagueRules.cap ?? 1403.9;
  }
  _n(v){ const x=Number(v); return Number.isFinite(x)?x:null; }
  _safeSum(arr,fn){ const v=arr.map(fn).filter(x=>x!=null); return v.length?v.reduce((a,b)=>a+b,0):null; }
  _safeAvg(arr,fn){ const v=arr.map(fn).filter(x=>x!=null); return v.length?v.reduce((a,b)=>a+b,0)/v.length:null; }
  _pos(p){ const s=String(p.position||p.pos||"").toUpperCase(); if(s.includes("QB"))return"QB";if(s.includes("RB"))return"RB";if(s.includes("WR"))return"WR";if(s.includes("TE"))return"TE";if(/DL|DE|DT|NT|EDGE/.test(s))return"DL";if(/LB/.test(s))return"LB";if(/DB|CB|S\b|FS|SS|SAFETY/.test(s))return"DB";return s.split(/[/,]/)[0]||"?"; }
  _score(p){ const w=this._n(p.weeklyProjection??p.weekly);if(w!=null&&w>0)return w;const s=this._n(p.seasonProjection??p.season);if(s!=null&&s>0)return s/17;const q=this._n(p.performancePpg??p.ppg);return q!=null&&q>0?q:null; }
  _unavailable(p){ return /OUT|IR|INJURED|SUSPEND/i.test(String(p.status||"")+" "+String(p.injury||"")+" "+String(p.rosterSlot||"")); }
  _taxi(p){ return /TAXI|MINOR/i.test(String(p.status||"")+" "+String(p.rosterSlot||"")); }
  optimalLineup(players){ const pool=players.filter(p=>!this._unavailable(p)&&this._score(p)!=null),used=new Set(),lineup=[],slots=[];this.starters.forEach((s,i)=>{for(let n=0;n<s.count;n++)slots.push({slot:s.slot,accept:s.accept,order:i*100+n});});slots.sort((a,b)=>a.accept.length-b.accept.length||a.order-b.order).forEach(s=>{const pick=pool.filter(p=>!used.has(p.id)&&s.accept.includes(this._pos(p))).sort((a,b)=>this._score(b)-this._score(a))[0];if(pick)used.add(pick.id);lineup.push({slot:s.slot,player:pick||null});});return{lineup,total:this._safeSum(lineup.filter(r=>r.player),r=>this._score(r.player)),filled:lineup.filter(r=>r.player).length,open:lineup.filter(r=>!r.player).length}; }
  usableDepth(players,ids){ return players.filter(p=>!ids.has(p.id)&&!this._taxi(p)&&!this._unavailable(p)&&this._score(p)!=null); }
  teamPillars(team){ const players=team.players||[],opt=this.optimalLineup(players),ids=new Set(opt.lineup.filter(r=>r.player).map(r=>r.player.id)),depth=this.usableDepth(players,ids),starters=opt.lineup.filter(r=>r.player).map(r=>r.player);const salary=this._safeSum(players,p=>this._n(p.salary)),dead=this._n(team.deadCap),used=salary==null&&dead==null?null:(salary||0)+(dead||0),room=used==null?null:this.cap-used,ages=starters.map(p=>this._n(p.age)).filter(a=>a!=null),age=ages.length?ages.reduce((a,b)=>a+b,0)/ages.length:null,picks=team.picks||[],draft=picks.reduce((s,p)=>s+(Number(p.round)===1?3:Number(p.round)===2?2:1),0);const positions=["QB","RB","WR","TE","DL","LB","DB"],byPos={};positions.forEach(pos=>{const demand=this.starters.filter(s=>s.accept.includes(pos)).reduce((n,s)=>n+s.count/s.accept.length,0),need=Math.max(1,Math.ceil(demand)),pool=players.filter(p=>this._pos(p)===pos&&this._score(p)!=null&&!this._unavailable(p)).sort((a,b)=>this._score(b)-this._score(a));byPos[pos]=this._safeAvg(pool.slice(0,need),p=>this._score(p));});const known=Object.values(byPos).filter(v=>v!=null),balance=known.length>=3?100-Math.min(100,this._std(known)*10):null;return{teamId:team.id,teamName:team.name,pillars:{legalStarters:{value:opt.total,filled:opt.filled,open:opt.open},usableDepth:{value:this._safeAvg(depth,p=>this._score(p)),count:depth.length},capHealth:{value:room==null?null:(room/this.cap)*100,room,used,cap:this.cap},competitiveWindow:{starterAge:age,mode:this._windowMode(age,draft,opt.total)},positionalBalance:{value:balance,byPos},draftCapital:{value:draft,picks:picks.length}},lineup:opt,depth}; }
  _std(a){const m=a.reduce((x,y)=>x+y,0)/a.length;return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/a.length);}
  _windowMode(age,draft,strength){if(age==null)return"unknown";if(age<=26&&draft>=4)return"rebuilding";if(age>=29&&strength!=null)return"contending";return"balanced";}
  _percentile(value,values){if(value==null)return null;const g=values.filter(v=>v!=null).sort((a,b)=>a-b);return g.length?100*g.filter(v=>v<=value).length/g.length:null;}
  _grade(s){if(s==null)return"N/A";if(s>=93)return"A";if(s>=88)return"A-";if(s>=83)return"B+";if(s>=78)return"B";if(s>=73)return"B-";if(s>=68)return"C+";if(s>=63)return"C";if(s>=58)return"C-";if(s>=50)return"D";return"F";}
  analyzeLeague(teams){const reports=teams.map(t=>this.teamPillars(t)),keys=[["legalStarters",r=>r.pillars.legalStarters.value],["usableDepth",r=>r.pillars.usableDepth.value],["capHealth",r=>r.pillars.capHealth.value],["positionalBalance",r=>r.pillars.positionalBalance.value],["draftCapital",r=>r.pillars.draftCapital.value]],weights={legalStarters:.38,usableDepth:.22,capHealth:.17,positionalBalance:.10,draftCapital:.06,competitiveWindow:.07},arrays={};keys.forEach(([k,f])=>arrays[k]=reports.map(f));return reports.map(r=>{const comps=[];keys.forEach(([k,f])=>{const p=this._percentile(f(r),arrays[k]);if(p!=null)comps.push({name:k,score:p,weight:weights[k]});});const ages=reports.map(x=>x.pillars.competitiveWindow.starterAge),ap=this._percentile(r.pillars.competitiveWindow.starterAge==null?null:-r.pillars.competitiveWindow.starterAge,ages.map(a=>a==null?null:-a));if(ap!=null)comps.push({name:"competitiveWindow",score:ap,weight:weights.competitiveWindow});const w=comps.reduce((s,c)=>s+c.weight,0),score=w?comps.reduce((s,c)=>s+c.score*c.weight,0)/w:null;return{...r,grade:this._grade(score),score,components:comps,confidence:Math.round((w||0)*100)};});}
  recommendFreeAgents(team,freeAgents,limit=10){const base=this.optimalLineup(team.players||[]),salary=this._safeSum(team.players||[],p=>this._n(p.salary)),dead=this._n(team.deadCap),capRoom=salary==null&&dead==null?null:this.cap-(salary||0)-(dead||0);return(freeAgents||[]).map(fa=>{const ev=this._score(fa);if(ev==null||this._unavailable(fa))return null;const next=this.optimalLineup([...(team.players||[]),fa]),gain=base.total!=null&&next.total!=null?Math.max(0,next.total-base.total):null,pos=this._pos(fa),same=(team.players||[]).filter(p=>this._pos(p)===pos&&this._score(p)!=null).sort((a,b)=>this._score(a)-this._score(b)),weak=same[0],vs=weak&&ev!=null?ev-this._score(weak):null;let fit=0;const reasons=[];if(gain!=null&&gain>0){fit+=40;reasons.push(`+${gain.toFixed(1)} to best legal lineup`);}if(vs!=null&&vs>0){fit+=25;reasons.push(`+${vs.toFixed(1)} FP/G vs ${weak.name}`);}if(capRoom!=null&&capRoom>5){fit+=15;reasons.push(`cap room $${capRoom.toFixed(1)}`);}const age=this._n(fa.age);if(age!=null&&age<=26){fit+=10;reasons.push(`age ${age}`);}return reasons.length?{player:fa,lineupGain:gain,vsWeakest:vs,fit,reasons,explanation:`${fa.name} for ${team.name}: ${reasons.join("; ")}.`}:null;}).filter(Boolean).sort((a,b)=>b.fit-a.fit||(b.lineupGain||0)-(a.lineupGain||0)).slice(0,limit);}
}
