/** GMS Locker analysis engine. Missing data remains null; open spots are not weaknesses. */
export class GMSAnalysisEngine {
  constructor(leagueRules = {}) {
    this.starters = leagueRules.starters || [
      { slot:"QB",count:1,accept:["QB"]},{slot:"SFX",count:1,accept:["QB","RB","WR","TE"]},
      { slot:"RB",count:2,accept:["RB"]},{slot:"WR",count:3,accept:["WR"]},{slot:"TE",count:1,accept:["TE"]},
      { slot:"RWT",count:1,accept:["RB","WR","TE"]},{slot:"DL",count:3,accept:["DL"]},
      { slot:"LB",count:2,accept:["LB"]},{slot:"DB",count:3,accept:["DB"]},{slot:"ID",count:2,accept:["DL","LB","DB"]}
    ];
    this.cap = leagueRules.cap ?? 1403.90;
  }
  _n(v){ const x=Number(v); return Number.isFinite(x)?x:null; }
  _safeSum(arr,fn){ const v=arr.map(fn).filter(x=>x!=null); return v.length?v.reduce((a,b)=>a+b,0):null; }
  _safeAvg(arr,fn){ const v=arr.map(fn).filter(x=>x!=null); return v.length?v.reduce((a,b)=>a+b,0)/v.length:null; }
  _pos(p){ const s=String(p.position||p.pos||"").toUpperCase(); if(s.includes("QB"))return"QB";if(s.includes("RB"))return"RB";if(s.includes("WR"))return"WR";if(s.includes("TE"))return"TE";if(/DL|DE|DT|NT|EDGE/.test(s))return"DL";if(/LB/.test(s))return"LB";if(/DB|CB|S\b|FS|SS|SAFETY/.test(s))return"DB";return s.split(/[/,]/)[0]||"?"; }
  _score(p){ const w=this._n(p.weeklyProjection??p.weekly);if(w!=null&&w>0)return w;const s=this._n(p.seasonProjection??p.season);if(s!=null&&s>0)return s/17;const q=this._n(p.performancePpg??p.ppg);return q!=null&&q>0?q:null; }
  _scoreSource(p){const w=this._n(p.weeklyProjection??p.weekly);if(w!=null&&w>0)return"weekly projection";const s=this._n(p.seasonProjection??p.season);if(s!=null&&s>0)return"season projection";const q=this._n(p.performancePpg??p.ppg);if(q!=null&&q>0)return"historical PPG";return"unavailable";}
  _unavailable(p){ return /OUT|IR|INJURED|SUSPEND/i.test(String(p.status||"")+" "+String(p.injury||"")+" "+String(p.rosterSlot||"")); }
  _taxi(p){ return /TAXI|MINOR/i.test(String(p.status||"")+" "+String(p.rosterSlot||"")); }
  optimalLineup(players){ const pool=players.filter(p=>!this._unavailable(p)&&this._score(p)!=null),used=new Set(),lineup=[],slots=[];this.starters.forEach((s,i)=>{for(let n=0;n<s.count;n++)slots.push({slot:s.slot,accept:s.accept,order:i*100+n});});slots.sort((a,b)=>a.accept.length-b.accept.length||a.order-b.order).forEach(s=>{const pick=pool.filter(p=>!used.has(p.id)&&s.accept.includes(this._pos(p))).sort((a,b)=>this._score(b)-this._score(a))[0];if(pick)used.add(pick.id);lineup.push({slot:s.slot,player:pick||null});});return{lineup,total:this._safeSum(lineup.filter(r=>r.player),r=>this._score(r.player)),filled:lineup.filter(r=>r.player).length,open:lineup.filter(r=>!r.player).length}; }
  usableDepth(players,ids){ return players.filter(p=>!ids.has(p.id)&&!this._taxi(p)&&!this._unavailable(p)&&this._score(p)!=null); }
  teamPillars(team){
    const players=team.players||[],opt=this.optimalLineup(players),ids=new Set(opt.lineup.filter(r=>r.player).map(r=>r.player.id)),depth=this.usableDepth(players,ids),starters=opt.lineup.filter(r=>r.player).map(r=>r.player);
    const salary=this._safeSum(players,p=>this._n(p.salary)),dead=this._n(team.deadCap),used=salary==null&&dead==null?null:(salary||0)+(dead||0),room=used==null?null:this.cap-used,ages=starters.map(p=>this._n(p.age)).filter(a=>a!=null),age=ages.length?ages.reduce((a,b)=>a+b,0)/ages.length:null,picks=team.picks||[],draft=picks.reduce((s,p)=>s+(Number(p.round)===1?3:Number(p.round)===2?2:1),0);
    const positions=["QB","RB","WR","TE","DL","LB","DB"],byPos={};positions.forEach(pos=>{const demand=this.starters.filter(s=>s.accept.includes(pos)).reduce((n,s)=>n+s.count/s.accept.length,0),need=Math.max(1,Math.ceil(demand)),pool=players.filter(p=>this._pos(p)===pos&&this._score(p)!=null&&!this._unavailable(p)).sort((a,b)=>this._score(b)-this._score(a));byPos[pos]=this._safeAvg(pool.slice(0,need),p=>this._score(p));});
    const known=Object.values(byPos).filter(v=>v!=null),balance=known.length>=3?100-Math.min(100,this._std(known)*10):null;
    const mode=this._windowMode(age,draft,opt.total);
    return{teamId:team.id,teamName:team.name,pillars:{
      legalStarters:{value:opt.total,filled:opt.filled,open:opt.open,reason:opt.total==null?"No reliable scoring input exists for enough eligible starters to calculate lineup strength.":`Best legal lineup totals ${opt.total.toFixed(1)} FP/G using ${opt.filled} scored starters. ${opt.open} lineup slot(s) are open, but open spots are not scored as weaknesses.`},
      usableDepth:{value:this._safeAvg(depth,p=>this._score(p)),count:depth.length,reason:depth.length?`There are ${depth.length} non-starter players with usable scoring data who are not taxi/minor or unavailable. Their average usable score is ${this._safeAvg(depth,p=>this._score(p))?.toFixed(1)??"unavailable"} FP/G.`:"No non-starter currently has enough usable scoring data to measure depth. This is treated as unavailable evidence, not automatic bad depth."},
      capHealth:{value:room==null?null:(room/this.cap)*100,room,used,cap:this.cap,reason:used==null?`Cap health is unavailable because salary/dead-cap data is incomplete. Missing salary is never treated as $0.`:`Known cap usage is $${used.toFixed(2)} against a $${this.cap.toFixed(2)} cap, leaving $${room.toFixed(2)} of known room.`},
      competitiveWindow:{starterAge:age,mode,reason:age==null?"Competitive window is uncertain because starter ages are incomplete.":`Starter age averages ${age.toFixed(1)}. Draft-capital score is ${draft}. Combined with known lineup strength, the roster currently profiles as ${mode}.`},
      positionalBalance:{value:balance,byPos,reason:balance==null?"Positional balance needs at least three position groups with reliable scoring data.":`Balance compares known scoring strength across QB, RB, WR, TE, DL, LB and DB groups. Lower spread between position groups produces a higher score.`},
      draftCapital:{value:draft,picks:picks.length,reason:picks.length?`${picks.length} known future pick(s) contribute a weighted draft-capital score of ${draft}; first-round picks carry the most weight, then seconds, then later rounds.`:"No future draft picks were returned in the synced data. This is reported as no known picks, not proof the team owns none."}
    },lineup:opt,depth};
  }
  _std(a){const m=a.reduce((x,y)=>x+y,0)/a.length;return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/a.length);}
  _windowMode(age,draft,strength){if(age==null)return"unknown";if(age<=26&&draft>=4)return"rebuilding";if(age>=29&&strength!=null)return"contending";return"balanced";}
  _percentile(value,values){if(value==null)return null;const g=values.filter(v=>v!=null).sort((a,b)=>a-b);return g.length?100*g.filter(v=>v<=value).length/g.length:null;}
  _grade(s){if(s==null)return"N/A";if(s>=93)return"A";if(s>=88)return"A-";if(s>=83)return"B+";if(s>=78)return"B";if(s>=73)return"B-";if(s>=68)return"C+";if(s>=63)return"C";if(s>=58)return"C-";if(s>=50)return"D";return"F";}
  analyzeLeague(teams){const reports=teams.map(t=>this.teamPillars(t)),keys=[["legalStarters",r=>r.pillars.legalStarters.value],["usableDepth",r=>r.pillars.usableDepth.value],["capHealth",r=>r.pillars.capHealth.value],["positionalBalance",r=>r.pillars.positionalBalance.value],["draftCapital",r=>r.pillars.draftCapital.value]],weights={legalStarters:.38,usableDepth:.22,capHealth:.17,positionalBalance:.10,draftCapital:.06,competitiveWindow:.07},arrays={};keys.forEach(([k,f])=>arrays[k]=reports.map(f));return reports.map(r=>{const comps=[];keys.forEach(([k,f])=>{const p=this._percentile(f(r),arrays[k]);if(p!=null)comps.push({name:k,score:p,weight:weights[k]});});const ages=reports.map(x=>x.pillars.competitiveWindow.starterAge),ap=this._percentile(r.pillars.competitiveWindow.starterAge==null?null:-r.pillars.competitiveWindow.starterAge,ages.map(a=>a==null?null:-a));if(ap!=null)comps.push({name:"competitiveWindow",score:ap,weight:weights.competitiveWindow});const w=comps.reduce((s,c)=>s+c.weight,0),score=w?comps.reduce((s,c)=>s+c.score*c.weight,0)/w:null;const ordered=[...comps].sort((a,b)=>(b.score*b.weight)-(a.score*a.weight));const strengths=ordered.slice(0,2).map(c=>`${c.name} (${c.score.toFixed(0)}th percentile)`),risks=[...comps].sort((a,b)=>a.score-b.score).slice(0,2).map(c=>`${c.name} (${c.score.toFixed(0)}th percentile)`);return{...r,grade:this._grade(score),score,components:comps,confidence:Math.round((w||0)*100),summary:score==null?"Overall grade is unavailable because too few pillars have reliable data.":`Overall ${this._grade(score)} (${score.toFixed(1)}/100). Strongest evidence: ${strengths.join(", ")||"unavailable"}. Biggest relative concerns: ${risks.join(", ")||"unavailable"}. Confidence is ${Math.round((w||0)*100)}% based on how many weighted pillars have usable data.`};});}
  recommendFreeAgents(team,freeAgents,limit=10){
    const base=this.optimalLineup(team.players||[]),salary=this._safeSum(team.players||[],p=>this._n(p.salary)),dead=this._n(team.deadCap),capRoom=salary==null&&dead==null?null:this.cap-(salary||0)-(dead||0);
    return(freeAgents||[]).map(fa=>{
      const ev=this._score(fa);if(ev==null||this._unavailable(fa))return null;
      const next=this.optimalLineup([...(team.players||[]),fa]),gain=base.total!=null&&next.total!=null?Math.max(0,next.total-base.total):null,pos=this._pos(fa),same=(team.players||[]).filter(p=>this._pos(p)===pos&&this._score(p)!=null).sort((a,b)=>this._score(a)-this._score(b)),weak=same[0],vs=weak&&ev!=null?ev-this._score(weak):null;
      let fit=0;const reasons=[],details=[];
      details.push(`Evaluation source: ${this._scoreSource(fa)} at ${ev.toFixed(1)} FP/G equivalent.`);
      if(gain!=null&&gain>0){fit+=40;reasons.push(`+${gain.toFixed(1)} to best legal lineup`);details.push(`Adding ${fa.name} raises the team's best legal weekly lineup from ${base.total.toFixed(1)} to ${next.total.toFixed(1)} FP/G, a ${gain.toFixed(1)}-point gain.`);}else if(gain===0){details.push(`${fa.name} does not currently crack the best legal starting lineup, so this is a depth/roster-value move rather than an immediate starter upgrade.`);}else{details.push(`Lineup impact cannot be calculated because the current roster lacks enough comparable scoring data.`);}
      if(vs!=null&&vs>0){fit+=25;reasons.push(`+${vs.toFixed(1)} FP/G vs ${weak.name}`);details.push(`At ${pos}, ${fa.name} scores ${vs.toFixed(1)} FP/G above the weakest currently scored ${pos}, ${weak.name}.`);}else if(!weak){details.push(`There is no comparable scored ${pos} on the roster, so GMS will not invent a positional weakness or replacement value.`);}else{details.push(`${fa.name} does not clearly outperform the weakest scored ${pos} on the current roster.`);}
      if(capRoom!=null&&fa.salary!=null){const post=capRoom-this._n(fa.salary);if(post>=0){fit+=15;reasons.push(`fits known cap`);details.push(`Known cap room is $${capRoom.toFixed(2)}. At a listed salary of $${this._n(fa.salary).toFixed(2)}, the move would leave about $${post.toFixed(2)} in known room.`);}else{details.push(`Listed salary would exceed currently known cap room by about $${Math.abs(post).toFixed(2)}.`);}}else if(capRoom!=null){details.push(`Team cap room is known at $${capRoom.toFixed(2)}, but this player's salary is unavailable, so affordability cannot be assumed.`);}else{details.push(`Cap fit is unavailable because team salary/dead-cap data is incomplete.`);}
      const age=this._n(fa.age);if(age!=null&&age<=26){fit+=10;reasons.push(`age ${age}`);details.push(`Age ${age} adds longer-term roster value and supports dynasty flexibility.`);}else if(age!=null){details.push(`Age ${age} is considered, but no youth bonus is applied.`);}else{details.push(`Age is unavailable, so no age-based value is added.`);}
      if(fa.injury)details.push(`Availability note: ${fa.injury}.`);
      if(!reasons.length)return null;
      return{player:fa,lineupGain:gain,vsWeakest:vs,fit,reasons,details,explanation:`${fa.name} is recommended for ${team.name} because ${reasons.join("; ")}. ${details.join(" ")}`};
    }).filter(Boolean).sort((a,b)=>b.fit-a.fit||(b.lineupGain||0)-(a.lineupGain||0)).slice(0,limit);
  }
}
