const PRIDE_LEAGUE_ID = "astbqxhwmk4b6bg9";
const FANTRAX_GENERAL = "https://www.fantrax.com/fxea/general/";
const ESPN_SCOREBOARD = "https://site.web.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard?limit=100";
const ESPN_HEALTH = "https://cdn.espn.com/core/nfl/scoreboard?xhr=1";
const TEAM_IDS = {ATL:1,BUF:2,CHI:3,CIN:4,CLE:5,DAL:6,DEN:7,DET:8,GB:9,TEN:10,IND:11,KC:12,LV:13,LAR:14,MIA:15,MIN:16,NE:17,NO:18,NYG:19,NYJ:20,PHI:21,ARI:22,PIT:23,LAC:24,SF:25,SEA:26,TB:27,WAS:28,WSH:28,CAR:29,JAX:30,BAL:33,HOU:34};
const YEAR = () => new Date().getUTCFullYear();
const DEPTH_URL = id => `https://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/${YEAR()}/teams/${id}/depthcharts`;
const ROSTER_URL = id => `https://site.api.espn.com/apis/site/v2/sports/football/nfl/teams/${id}/roster`;

function cors(){return {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET,OPTIONS","Access-Control-Allow-Headers":"Accept,Content-Type","Cache-Control":"no-store"};}
function json(body,status=200){return new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json; charset=utf-8",...cors()}});}
function headers(extra={}){return {Accept:"application/json, text/plain, */*","Accept-Language":"en-US,en;q=0.9","User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36",Referer:"https://www.espn.com/",...extra};}
async function fetchJson(url){const r=await fetch(url,{headers:headers(),cf:{cacheTtl:30,cacheEverything:true}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json();}
function clean(v){return String(v||"").replace(/\s+/g," ").trim();}
function teamCode(v){return clean(v).toUpperCase().replace(/[^A-Z]/g,"").replace(/^WSH$/,"WAS").slice(0,4);}
function athleteName(row){return clean(row?.athlete?.displayName||row?.athlete?.fullName||row?.displayName||row?.fullName||row?.name||row?.player?.displayName||row?.player?.fullName);}
function athleteId(value){const t=String(value||"");return t.match(/\/athletes\/(\d+)/)?.[1]||t.match(/^(\d+)$/)?.[1]||null;}
function slotBase(key,position){const raw=clean(key||position?.abbreviation||position?.name).toUpperCase().replace(/[^A-Z0-9]/g,"");const aliases={LEFTWIDERECEIVER:"LWR",RIGHTWIDERECEIVER:"RWR",SLOTWIDERECEIVER:"SWR",SLOTRECEIVER:"SWR",LEFTCORNERBACK:"LCB",RIGHTCORNERBACK:"RCB",NICKELCORNERBACK:"NCB",NICKELBACK:"NCB",FREESAFETY:"FS",STRONGSAFETY:"SS",MIDDLELINEBACKER:"MIKE",WEAKSIDELINEBACKER:"WILL",STRONGSIDELINEBACKER:"SAM",LEFTDEFENSIVEEND:"LDE",RIGHTDEFENSIVEEND:"RDE",NOSETACKLE:"NT"};if(aliases[raw])return aliases[raw];if(/^(LWR|RWR|SWR|XWR|ZWR|LCB|RCB|NCB|SCB|FS|SS|MIKE|WILL|SAM|LOLB|ROLB|LDE|RDE|NT|DT|RB|QB|TE|FB|WR|CB|LB|DE|KR|PR|LS|P|K)$/.test(raw))return raw;return raw.slice(0,10)||"DEPTH";}
function collectRosterNames(node,map){if(!node)return;if(Array.isArray(node)){node.forEach(item=>collectRosterNames(item,map));return;}if(typeof node!=="object")return;const id=String(node.id||node.athlete?.id||"");const name=athleteName(node)||athleteName(node.athlete);if(id&&name)map.set(id,name);Object.values(node).forEach(value=>collectRosterNames(value,map));}
function parseDepth(depth,team,nameMap){const rows=[],seen=new Set();for(const chart of depth?.items||[]){for(const [key,group] of Object.entries(chart?.positions||{})){const base=slotBase(key,group?.position);const athletes=Array.isArray(group?.athletes)?group.athletes:Array.isArray(group?.players)?group.players:[];athletes.forEach((row,index)=>{const ref=row?.athlete?.$ref||row?.$ref||"";const id=String(row?.athlete?.id||row?.id||athleteId(ref)||"");const name=athleteName(row)||athleteName(row?.athlete)||nameMap.get(id)||"";if(!name)return;const rank=Number(row?.rank??row?.depth??row?.order)||index+1;const slot=`${base}${rank}`;const unique=`${team}|${name.toLowerCase()}|${slot}`;if(seen.has(unique))return;seen.add(unique);rows.push({name,athleteId:id||null,team,slot,baseSlot:base,depth:rank});});}}return rows;}
async function oneTeam(team){const id=TEAM_IDS[team];if(!id)return{team,rows:[],error:"Unknown ESPN team mapping"};try{const [depth,roster]=await Promise.all([fetchJson(DEPTH_URL(id)),fetchJson(ROSTER_URL(id))]);const names=new Map();collectRosterNames(roster,names);return{team,rows:parseDepth(depth,team,names),error:null};}catch(error){return{team,rows:[],error:String(error?.message||error)};}}
async function depthCharts(url){const teams=[...new Set(String(url.searchParams.get("teams")||"").split(",").map(teamCode).filter(Boolean))].slice(0,32);if(!teams.length)return json({teams:{},players:[],source:"ESPN NFL depth charts",syncedAt:new Date().toISOString(),warning:"No NFL teams requested"});const results=await Promise.all(teams.map(oneTeam)),byTeam={},players=[],errors=[];for(const result of results){byTeam[result.team]=result.rows;players.push(...result.rows);if(result.error)errors.push(`${result.team}: ${result.error}`);}return json({teams:byTeam,players,source:"ESPN NFL depth charts",syncedAt:new Date().toISOString(),season:YEAR(),requestedTeams:teams.length,returnedTeams:Object.keys(byTeam).length,errors});}

async function fantraxPublic(endpoint){const u=new URL(FANTRAX_GENERAL+endpoint);if(endpoint==="getPlayerIds")u.searchParams.set("sport","NFL");else u.searchParams.set("leagueId",PRIDE_LEAGUE_ID);const response=await fetch(u.toString(),{headers:headers(),cf:{cacheTtl:30,cacheEverything:true}});if(!response.ok)throw new Error(`${endpoint} HTTP ${response.status}`);return response.json();}
function buildPlayerMap(payload){const map=new Map();const src=payload?.playerIds||payload?.players||payload||{};if(Array.isArray(src)){for(const row of src){const id=String(row?.id||row?.fantraxId||row?.playerId||"");if(!id)continue;map.set(id,{name:clean(row?.name||row?.playerName)||null,nflTeam:clean(row?.team||row?.nflTeam)||null,position:clean(row?.position||row?.pos)||null});}}else if(src&&typeof src==="object"){for(const [key,value] of Object.entries(src)){const row=value&&typeof value==="object"?value:{name:value};const id=String(row?.fantraxId||row?.id||key);map.set(id,{name:clean(row?.name||row?.playerName||(typeof value==="string"?value:""))||null,nflTeam:clean(row?.team||row?.nflTeam)||null,position:clean(row?.position||row?.pos)||null});}}return map;}
function formatName(raw){const text=clean(raw);if(!text)return "Unknown";if(text.includes(",")){const parts=text.split(",").map(s=>s.trim());if(parts[0]&&parts[1])return `${parts[1]} ${parts[0]}`;}return text;}
function normalizeRosterTeam(id,row,playerMap){const items=Array.isArray(row?.rosterItems)?row.rosterItems:[];const players=items.map(item=>{const pid=String(item?.id||item?.player?.id||"");const meta=playerMap.get(pid)||{};const contractYears=item?.contract?.name||item?.contract?.smallId||item?.contract||null;return{id:pid,name:formatName(meta.name||item?.name||item?.player?.name)||"Unknown",position:clean(item?.position||meta.position||item?.player?.position)||"",nflTeam:clean(meta.nflTeam||item?.team||item?.player?.team)||"",salary:item?.salary??item?.player?.salary??null,contract:contractYears,rosterSlot:item?.rosterSlot||item?.status||""};});return{id,name:row?.teamName||id,salaryCap:row?.salaryCap??null,players};}
async function prideLeague(){try{const [rosters,info,picks,playerIds]=await Promise.all([fantraxPublic("getTeamRosters"),fantraxPublic("getLeagueInfo").catch(()=>null),fantraxPublic("getDraftPicks").catch(()=>null),fantraxPublic("getPlayerIds").catch(()=>({}))]);const playerMap=buildPlayerMap(playerIds);const teams=Object.entries(rosters?.rosters||{}).map(([id,row])=>normalizeRosterTeam(id,row,playerMap));const named=teams.reduce((n,t)=>n+(t.players||[]).filter(p=>p.name&&p.name!=="Unknown").length,0);const total=teams.reduce((n,t)=>n+(t.players||[]).length,0);return json({ok:true,leagueId:PRIDE_LEAGUE_ID,leagueName:info?.leagueName||info?.name||"Pride Dynasty",teams,picks:picks?.futureDraftPicks||picks||null,playerMapSize:playerMap.size,namedPlayers:named,totalPlayers:total,syncedAt:new Date().toISOString(),source:"Fantrax live read-only"});}catch(error){return json({ok:false,error:"Fantrax public league sync failed",detail:String(error?.message||error),leagueId:PRIDE_LEAGUE_ID},502);}}
async function currentGames(){try{const data=await fetchJson(ESPN_SCOREBOARD);const events=data?.events||data?.content?.sbData?.events||[];const schedule=events.map(event=>{const competition=event?.competitions?.[0]||{};const competitors=competition?.competitors||[];const home=competitors.find(x=>x.homeAway==="home")||{};const away=competitors.find(x=>x.homeAway==="away")||{};const team=row=>({id:row?.team?.id||null,name:row?.team?.displayName||row?.team?.name||null,abbreviation:row?.team?.abbreviation||null,score:row?.score??null});return{id:event?.id||null,date:event?.date||competition?.date||null,status:event?.status?.type?.shortDetail||event?.status?.type?.description||"Scheduled",venue:competition?.venue?.fullName||null,home:team(home),away:team(away)};});return json({schedule,source:"ESPN NFL scoreboard",syncedAt:new Date().toISOString()});}catch(error){return json({schedule:[],error:String(error?.message||error),source:"ESPN NFL scoreboard",syncedAt:new Date().toISOString()},502);}}
async function health(){const checks={worker:true,fantrax:false,espn:false};const errors=[];try{const r=await fetch(FANTRAX_GENERAL+"getPlayerIds?sport=NFL",{headers:headers()});checks.fantrax=r.ok;if(!r.ok)errors.push(`Fantrax HTTP ${r.status}`);}catch(error){errors.push(`Fantrax: ${String(error?.message||error)}`);}try{const r=await fetch(ESPN_HEALTH,{headers:headers()});checks.espn=r.ok;if(!r.ok)errors.push(`ESPN HTTP ${r.status}`);}catch(error){errors.push(`ESPN: ${String(error?.message||error)}`);}return json({ok:checks.worker&&checks.fantrax&&checks.espn,service:"gmslocker-api",version:"3.0.0-public-no-auth",auth:false,leagueId:PRIDE_LEAGUE_ID,checks,errors,checkedAt:new Date().toISOString()});}

export default {async fetch(request){const url=new URL(request.url);if(request.method==="OPTIONS")return new Response(null,{status:204,headers:cors()});if(request.method!=="GET")return json({error:"Read-only API"},405);if(url.pathname==="/health")return health();if(url.pathname==="/public/pride-league"||url.pathname==="/league-data")return prideLeague();if(url.pathname==="/depth-charts")return depthCharts(url);if(url.pathname==="/current-games")return currentGames();if(url.pathname.startsWith("/auth/")||url.pathname.startsWith("/account/")||url.pathname==="/chat"||url.pathname.startsWith("/trade-"))return json({error:"Authentication has been removed. This production API is read-only."},410);return json({error:"Not found"},404);}};
