const PRIDE_LEAGUE_ID = "astbqxhwmk4b6bg9";
const FANTRAX_GENERAL = "https://www.fantrax.com/fxea/general/";
const FANTRAX_PA = "https://www.fantrax.com/fxpa/req";
const SEASON_PROJ = "PROJECTION_0_23l_SEASON";
const WEEKLY_PROJ = "PROJECTION_0_23l_EVENT_PROJECTED_WEEKLY";
const ESPN_SCOREBOARD = "https://site.web.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard?limit=100";
const ESPN_HEALTH = "https://cdn.espn.com/core/nfl/scoreboard?xhr=1";
const MY_TEAM_ID = "nsf1b7esmk4b6bgd";
const MY_TEAM_NAME = "Capitol Carnage";
const TEAM_IDS = {ATL:1,BUF:2,CHI:3,CIN:4,CLE:5,DAL:6,DEN:7,DET:8,GB:9,TEN:10,IND:11,KC:12,LV:13,LAR:14,MIA:15,MIN:16,NE:17,NO:18,NYG:19,NYJ:20,PHI:21,ARI:22,PIT:23,LAC:24,SF:25,SEA:26,TB:27,WAS:28,WSH:28,CAR:29,JAX:30,BAL:33,HOU:34};
const YEAR = () => new Date().getUTCFullYear();
const DEPTH_URL = id => `https://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/${YEAR()}/teams/${id}/depthcharts`;
const ROSTER_URL = id => `https://site.web.api.espn.com/apis/site/v2/sports/football/nfl/teams/${id}/roster`;

function cors(){return {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET,POST,OPTIONS","Access-Control-Allow-Headers":"Accept,Content-Type","Cache-Control":"no-store"};}
function json(body,status=200){return new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json; charset=utf-8",...cors()}});}
function headers(extra={}){return {Accept:"application/json, text/plain, */*","Accept-Language":"en-US,en;q=0.9","User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36",Referer:"https://www.espn.com/",...extra};}
async function fetchJson(url){const r=await fetch(url,{headers:headers(),cf:{cacheTtl:30,cacheEverything:true}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json();}
function clean(v){return String(v||"").replace(/\s+/g," ").trim();}
function teamCode(v){return clean(v).toUpperCase().replace(/[^A-Z]/g,"").replace(/^WSH$/,"WAS").slice(0,4);}
function num(value){if(value==null||value==="")return null;const parsed=Number(String(value).replace(/[^0-9.\-]/g,""));return Number.isFinite(parsed)?parsed:null;}
function plain(value){return String(value==null?"":value).replace(/<[^>]*>/g," ").replace(/&nbsp;/g," ").replace(/\s+/g," ").trim();}
function formatName(raw){const text=clean(raw);if(!text)return "Unknown";if(text.includes(",")){const parts=text.split(",").map(s=>s.trim());if(parts[0]&&parts[1])return `${parts[1]} ${parts[0]}`;}return text;}
function athleteName(row){return clean(row?.athlete?.displayName||row?.athlete?.fullName||row?.displayName||row?.fullName||row?.name||row?.player?.displayName||row?.player?.fullName);}
function athleteId(value){const t=String(value||"");return t.match(/\/athletes\/(\d+)/)?.[1]||t.match(/^(\d+)$/)?.[1]||null;}
function slotBase(key,position){const raw=clean(key||position?.abbreviation||position?.name).toUpperCase().replace(/[^A-Z0-9]/g,"");const aliases={LEFTWIDERECEIVER:"LWR",RIGHTWIDERECEIVER:"RWR",SLOTWIDERECEIVER:"SWR",SLOTRECEIVER:"SWR",LEFTCORNERBACK:"LCB",RIGHTCORNERBACK:"RCB",NICKELCORNERBACK:"NCB",NICKELBACK:"NCB",FREESAFETY:"FS",STRONGSAFETY:"SS",MIDDLELINEBACKER:"MIKE",WEAKSIDELINEBACKER:"WILL",STRONGSIDELINEBACKER:"SAM",LEFTDEFENSIVEEND:"LDE",RIGHTDEFENSIVEEND:"RDE",NOSETACKLE:"NT"};if(aliases[raw])return aliases[raw];if(/^(LWR|RWR|SWR|XWR|ZWR|LCB|RCB|NCB|SCB|FS|SS|MIKE|WILL|SAM|LOLB|ROLB|LDE|RDE|NT|DT|RB|QB|TE|FB|WR|CB|LB|DE|KR|PR|LS|P|K)$/.test(raw))return raw;return raw.slice(0,10)||"DEPTH";}
function collectRosterNames(node,map){if(!node)return;if(Array.isArray(node)){node.forEach(item=>collectRosterNames(item,map));return;}if(typeof node!=="object")return;const id=String(node.id||node.athlete?.id||"");const name=athleteName(node)||athleteName(node.athlete);if(id&&name)map.set(id,name);Object.values(node).forEach(value=>collectRosterNames(value,map));}
function parseDepth(depth,team,nameMap){const rows=[],seen=new Set();for(const chart of depth?.items||[]){for(const [key,group] of Object.entries(chart?.positions||{})){const base=slotBase(key,group?.position);const athletes=Array.isArray(group?.athletes)?group.athletes:Array.isArray(group?.players)?group.players:[];athletes.forEach((row,index)=>{const ref=row?.athlete?.$ref||row?.$ref||"";const id=String(row?.athlete?.id||row?.id||athleteId(ref)||"");const name=athleteName(row)||athleteName(row?.athlete)||nameMap.get(id)||"";if(!name)return;const rank=Number(row?.rank??row?.depth??row?.order)||index+1;const slot=`${base}${rank}`;const unique=`${team}|${name.toLowerCase()}|${slot}`;if(seen.has(unique))return;seen.add(unique);rows.push({name,athleteId:id||null,team,slot,baseSlot:base,depth:rank});});}}return rows;}
async function oneTeam(team){const id=TEAM_IDS[team];if(!id)return{team,rows:[],error:"Unknown ESPN team mapping"};try{let depth=null,roster=null,err=null;try{depth=await fetchJson(DEPTH_URL(id));}catch(e){err=String(e?.message||e);}try{roster=await fetchJson(ROSTER_URL(id));}catch(_){}const names=new Map();if(roster)collectRosterNames(roster,names);if(!depth)return{team,rows:[],error:err||"No depth chart"};return{team,rows:parseDepth(depth,team,names),error:null};}catch(error){return{team,rows:[],error:String(error?.message||error)};}}
async function depthCharts(url){const teams=[...new Set(String(url.searchParams.get("teams")||"").split(",").map(teamCode).filter(Boolean))].slice(0,32);if(!teams.length)return json({teams:{},players:[],source:"ESPN NFL depth charts",syncedAt:new Date().toISOString(),warning:"No NFL teams requested"});const results=await Promise.all(teams.map(oneTeam)),byTeam={},players=[],errors=[];for(const result of results){byTeam[result.team]=result.rows;players.push(...result.rows);if(result.error)errors.push(`${result.team}: ${result.error}`);}return json({teams:byTeam,players,source:"ESPN NFL depth charts",syncedAt:new Date().toISOString(),season:YEAR(),requestedTeams:teams.length,returnedTeams:Object.keys(byTeam).length,errors});}
async function fantraxPublic(endpoint){const u=new URL(FANTRAX_GENERAL+endpoint);if(endpoint==="getPlayerIds")u.searchParams.set("sport","NFL");else u.searchParams.set("leagueId",PRIDE_LEAGUE_ID);const response=await fetch(u.toString(),{headers:headers(),cf:{cacheTtl:30,cacheEverything:true}});if(!response.ok)throw new Error(`${endpoint} HTTP ${response.status}`);return response.json();}
function buildPlayerMap(payload){const map=new Map();const src=payload?.playerIds||payload?.players||payload||{};if(Array.isArray(src)){for(const row of src){const id=String(row?.id||row?.fantraxId||row?.playerId||"");if(!id)continue;map.set(id,{name:clean(row?.name||row?.playerName)||null,nflTeam:clean(row?.team||row?.nflTeam)||null,position:clean(row?.position||row?.pos)||null});}}else if(src&&typeof src==="object"){for(const [key,value] of Object.entries(src)){const row=value&&typeof value==="object"?value:{name:value};const id=String(row?.fantraxId||row?.id||key);map.set(id,{name:clean(row?.name||row?.playerName||(typeof value==="string"?value:""))||null,nflTeam:clean(row?.team||row?.nflTeam)||null,position:clean(row?.position||row?.pos)||null});}}return map;}
function normalizeRosterTeam(id,row,playerMap){const items=Array.isArray(row?.rosterItems)?row.rosterItems:[];const players=items.map(item=>{const pid=String(item?.id||item?.player?.id||"");const meta=playerMap.get(pid)||{};const contractYears=item?.contract?.name||item?.contract?.smallId||item?.contract||null;return{id:pid,name:formatName(meta.name||item?.name||item?.player?.name)||"Unknown",position:clean(item?.position||meta.position||item?.player?.position)||"",nflTeam:clean(meta.nflTeam||item?.team||item?.player?.team)||"",salary:item?.salary??item?.player?.salary??null,contract:contractYears,rosterSlot:item?.rosterSlot||item?.status||""};});return{id,name:row?.teamName||id,salaryCap:row?.salaryCap??null,players};}
function parseStats(response){const data=response?.data||{};const headers=data.tableHeader?.cells||[];const rows=data.statsTable||[];const index={};headers.forEach((header,i)=>{index[header.key||header.shortName||String(i)]=i;});const cell=(row,key,fallback)=>{const i=index[key]==null?fallback:index[key];return row.cells?.[i]?.content;};const players={};for(const row of rows){const scorer=row.scorer||{};const id=String(scorer.scorerId||row.scorerId||"");if(!id)continue;players[id]={id,name:formatName(scorer.name||id),nflTeam:scorer.teamShortName||null,position:plain(scorer.position||scorer.posShortNames||""),fpts:num(cell(row,"fpts",7)),ppg:num(cell(row,"fptsPerGame",8)),salary:num(cell(row,"salary",5)),rank:num(cell(row,"rankOv",0)),opponent:plain(cell(row,"opponent",4)),bye:num(cell(row,"bye",9))};}return players;}
async function fetchProjectionPage(seasonOrProjection,statusOrTeamFilter,pageNumber){const body=JSON.stringify({msgs:[{method:"getPlayerStats",data:{leagueId:PRIDE_LEAGUE_ID,pageNumber,maxResultsPerPage:750,view:"STATS",seasonOrProjection,statusOrTeamFilter,sortType:"SCORE",sortDirection:-1}}]});const response=await fetch(`${FANTRAX_PA}?leagueId=${encodeURIComponent(PRIDE_LEAGUE_ID)}`,{method:"POST",headers:headers({"Content-Type":"application/json"}),body});if(!response.ok)throw new Error(`fxpa projections HTTP ${response.status}`);const batch=await response.json();const resp=batch.responses?.[0]||{};return{players:parseStats(resp),pages:resp?.data?.paginatedResultSet?.totalNumPages||1,total:resp?.data?.paginatedResultSet?.totalNumResults||0};}
async function fetchProjectionMap(seasonOrProjection,statusOrTeamFilter="ALL_TAKEN",allPages=false){const first=await fetchProjectionPage(seasonOrProjection,statusOrTeamFilter,1);if(!allPages||first.pages<=1)return first.players;const maxPages=Math.min(first.pages,12);const rest=await Promise.all(Array.from({length:maxPages-1},(_,i)=>fetchProjectionPage(seasonOrProjection,statusOrTeamFilter,i+2).catch(()=>({players:{}}))));const merged={...first.players};for(const page of rest)Object.assign(merged,page.players||{});return merged;}
async function prideLeague(){try{const [rosters,info,picks,playerIds,seasonMap,weeklyMap]=await Promise.all([fantraxPublic("getTeamRosters"),fantraxPublic("getLeagueInfo").catch(()=>null),fantraxPublic("getDraftPicks").catch(()=>null),fantraxPublic("getPlayerIds").catch(()=>({})),fetchProjectionMap(SEASON_PROJ).catch(()=>({})),fetchProjectionMap(WEEKLY_PROJ).catch(()=>({}))]);const playerMap=buildPlayerMap(playerIds);const teams=Object.entries(rosters?.rosters||{}).map(([id,row])=>{const team=normalizeRosterTeam(id,row,playerMap);team.players=(team.players||[]).map(p=>{const season=seasonMap[p.id]||{};const weekly=weeklyMap[p.id]||{};return{...p,name:p.name&&p.name!=="Unknown"?p.name:(season.name||weekly.name||p.name),position:p.position||season.position||weekly.position||"",nflTeam:p.nflTeam||season.nflTeam||weekly.nflTeam||"",seasonProjection:season.fpts??null,weeklyProjection:weekly.fpts??weekly.ppg??null,ppg:season.ppg??weekly.ppg??null,rank:season.rank??null,opponent:weekly.opponent||season.opponent||null,bye:season.bye??weekly.bye??null};});return team;});const named=teams.reduce((n,t)=>n+(t.players||[]).filter(p=>p.name&&p.name!=="Unknown").length,0);const total=teams.reduce((n,t)=>n+(t.players||[]).length,0);const withProj=teams.reduce((n,t)=>n+(t.players||[]).filter(p=>p.seasonProjection!=null||p.weeklyProjection!=null).length,0);return json({ok:true,leagueId:PRIDE_LEAGUE_ID,leagueName:info?.leagueName||info?.name||"Pride Dynasty",teams,picks:picks?.futureDraftPicks||picks||null,playerMapSize:playerMap.size,namedPlayers:named,projectedPlayers:withProj,totalPlayers:total,projectionSource:"Fantrax fxpa season+weekly",syncedAt:new Date().toISOString(),source:"Fantrax live read-only"});}catch(error){return json({ok:false,error:"Fantrax public league sync failed",detail:String(error?.message||error),leagueId:PRIDE_LEAGUE_ID},502);}}
function posKey(pos){const p=String(pos||"").toUpperCase();if(p.includes("QB")||p==="SFX")return "QB";if(p.includes("RB"))return "RB";if(p.includes("WR")||p==="RWT")return "WR";if(p.includes("TE"))return "TE";if(p.includes("LB"))return "LB";if(p.includes("DB")||p.includes("CB")||p==="S"||p.includes("FS")||p.includes("SS"))return "DB";if(p.includes("DL")||p.includes("DE")||p.includes("DT"))return "DL";return p.slice(0,3)||"FLEX";}
function rosterByPos(players){const map={};for(const p of players||[]){const k=posKey(p.position);(map[k]||=[]).push(p);}for(const k of Object.keys(map)){map[k].sort((a,b)=>(b.seasonProjection||b.ppg||0)-(a.seasonProjection||a.ppg||0));}return map;}
function scorePickup(fa,myByPos){const k=posKey(fa.position);const mine=myByPos[k]||[];const faPts=fa.fpts||fa.ppg||0;const worst=mine.length?(mine[mine.length-1].seasonProjection||mine[mine.length-1].ppg||0):0;const best=mine.length?(mine[0].seasonProjection||mine[0].ppg||0):0;const depth=mine.length;let gain=faPts-worst;if(depth<=1)gain+=15;else if(depth<=2)gain+=8;if(faPts>best)gain+=10;return{gain,depth,worst,best,pos:k};}
async function waivers(url){try{const all=String(url.searchParams.get("all")||"1")!=="0";const limit=Number(url.searchParams.get("limit")||(all?99999:200));const [leagueRes,faMap]=await Promise.all([prideLeague(),fetchProjectionMap(SEASON_PROJ,"ALL_AVAILABLE",true).catch(()=>({}))]);const league=JSON.parse(await leagueRes.text());if(!league.ok)return json(league,502);const my=(league.teams||[]).find(t=>t.id===MY_TEAM_ID||/capitol carnage/i.test(t.name||""))||null;const myByPos=rosterByPos(my?.players||[]);const fas=Object.values(faMap).map(fa=>{const scored=scorePickup(fa,myByPos);return{id:fa.id,name:fa.name,position:fa.position||scored.pos,nflTeam:fa.nflTeam,seasonProjection:fa.fpts,ppg:fa.ppg,rank:fa.rank,needPos:scored.pos,depthAtPos:scored.depth,replaceTarget:scored.worst,upgradeGain:Math.round(scored.gain*10)/10,verdict:scored.gain>=25?"PRIORITY":scored.gain>=12?"TARGET":scored.gain>=5?"WATCH":"PASS"};}).sort((a,b)=>b.upgradeGain-a.upgradeGain);const best=fas.filter(f=>f.verdict!=="PASS").slice(0,50);return json({ok:true,teamId:my?.id||MY_TEAM_ID,teamName:my?.name||MY_TEAM_NAME,freeAgentCount:fas.length,freeAgents:fas.slice(0,limit),recommendations:best,importedAll:all,syncedAt:new Date().toISOString(),source:"Fantrax full FA pool + projections vs Capitol Carnage"});}catch(error){return json({ok:false,error:String(error?.message||error)},502);}}
async function bestMoves(url){try{const n=Math.min(20,Number(url.searchParams.get("limit")||10));const w=await waivers(new URL("https://x/waivers?all=1"));const data=JSON.parse(await w.text());if(!data.ok)return json(data,502);const moves=(data.recommendations||[]).slice(0,n).map((r,i)=>({rank:i+1,type:"WAIVER",action:`Pick up ${r.name}`,reason:`${r.needPos} depth ${r.depthAtPos}; +${r.upgradeGain} proj vs current bottom`,player:r}));return json({ok:true,teamName:data.teamName,moves,count:moves.length,freeAgentCount:data.freeAgentCount,syncedAt:new Date().toISOString()});}catch(error){return json({ok:false,error:String(error?.message||error)},502);}}
async function tradeAnalysis(request){try{let body={};if(request.method==="POST")body=await request.json().catch(()=>({}));const url=new URL(request.url);const teamAId=body.teamA||url.searchParams.get("teamA")||MY_TEAM_ID;const teamBId=body.teamB||url.searchParams.get("teamB");const giveA=new Set((body.giveA||String(url.searchParams.get("giveA")||"").split(",")).map(String).filter(Boolean));const giveB=new Set((body.giveB||String(url.searchParams.get("giveB")||"").split(",")).map(String).filter(Boolean));const leagueRes=await prideLeague();const league=JSON.parse(await leagueRes.text());if(!league.ok)return json(league,502);const teamA=(league.teams||[]).find(t=>String(t.id)===String(teamAId));const teamB=(league.teams||[]).find(t=>String(t.id)===String(teamBId));if(!teamA||!teamB)return json({error:"Both teams required"},400);const aPlayers=(teamA.players||[]).filter(p=>giveA.has(String(p.id)));const bPlayers=(teamB.players||[]).filter(p=>giveB.has(String(p.id)));let suggestion=null;if(!aPlayers.length&&!bPlayers.length){const aSorted=[...(teamA.players||[])].sort((x,y)=>(y.seasonProjection||0)-(x.seasonProjection||0));const bSorted=[...(teamB.players||[])].sort((x,y)=>(y.seasonProjection||0)-(x.seasonProjection||0));suggestion={note:"No players selected — showing top projection assets each side",topA:aSorted.slice(0,5).map(p=>({id:p.id,name:p.name,position:p.position,seasonProjection:p.seasonProjection})),topB:bSorted.slice(0,5).map(p=>({id:p.id,name:p.name,position:p.position,seasonProjection:p.seasonProjection}))};}const sum=arr=>arr.reduce((n,p)=>n+(p.seasonProjection||p.ppg||0),0);const aPts=sum(aPlayers);const bPts=sum(bPlayers);const delta=Math.round((bPts-aPts)*10)/10;let verdict="EVEN";if(delta>=20)verdict="ACCEPT";else if(delta>=8)verdict="LEAN ACCEPT";else if(delta<=-20)verdict="REJECT";else if(delta<=-8)verdict="LEAN REJECT";return json({ok:true,teamA:{id:teamA.id,name:teamA.name,giving:aPlayers,projectionOut:Math.round(aPts*10)/10},teamB:{id:teamB.id,name:teamB.name,giving:bPlayers,projectionOut:Math.round(bPts*10)/10},netGainForA:delta,verdict,summary:`${teamA.name} sends ${aPlayers.length} player(s) (${Math.round(aPts)} proj) for ${bPlayers.length} player(s) (${Math.round(bPts)} proj). Net for ${teamA.name}: ${delta>=0?"+":""}${delta}.`,suggestion,syncedAt:new Date().toISOString()});}catch(error){return json({ok:false,error:String(error?.message||error)},502);}}
async function currentGames(){try{const data=await fetchJson(ESPN_SCOREBOARD);const events=data?.events||data?.content?.sbData?.events||[];const schedule=events.map(event=>{const competition=event?.competitions?.[0]||{};const competitors=competition?.competitors||[];const home=competitors.find(x=>x.homeAway==="home")||{};const away=competitors.find(x=>x.homeAway==="away")||{};const team=row=>({id:row?.team?.id||null,name:row?.team?.displayName||row?.team?.name||null,abbreviation:row?.team?.abbreviation||null,score:row?.score??null});return{id:event?.id||null,date:event?.date||competition?.date||null,status:event?.status?.type?.shortDetail||event?.status?.type?.description||"Scheduled",venue:competition?.venue?.fullName||null,home:team(home),away:team(away)};});return json({schedule,source:"ESPN NFL scoreboard",syncedAt:new Date().toISOString()});}catch(error){return json({schedule:[],error:String(error?.message||error),source:"ESPN NFL scoreboard",syncedAt:new Date().toISOString()},502);}}
async function health(){const checks={worker:true,fantrax:false,espn:false};const errors=[];try{const r=await fetch(FANTRAX_GENERAL+"getPlayerIds?sport=NFL",{headers:headers()});checks.fantrax=r.ok;if(!r.ok)errors.push(`Fantrax HTTP ${r.status}`);}catch(error){errors.push(`Fantrax: ${String(error?.message||error)}`);}try{const r=await fetch(ESPN_HEALTH,{headers:headers()});checks.espn=r.ok;if(!r.ok)errors.push(`ESPN HTTP ${r.status}`);}catch(error){errors.push(`ESPN: ${String(error?.message||error)}`);}return json({ok:checks.worker&&checks.fantrax&&checks.espn,service:"gmslocker-api",version:"3.2.1-full-fa-pool",auth:false,leagueId:PRIDE_LEAGUE_ID,checks,errors,checkedAt:new Date().toISOString()});}
async function news(){try{const endpoints=["https://site.web.api.espn.com/apis/site/v2/sports/football/nfl/news?limit=25","https://cdn.espn.com/core/nfl/index?xhr=1"];for(const endpoint of endpoints){try{const data=await fetchJson(endpoint);const articles=(data.articles||data.content?.feed||[]).slice(0,25).map(a=>({id:String(a.id||a.headline||Math.random()),headline:clean(a.headline||a.title||""),description:clean(a.description||a.summary||""),published:a.published||a.publishedAt||null,link:a.links?.web?.href||a.link||null})).filter(a=>a.headline);if(articles.length)return json({articles,source:"ESPN",syncedAt:new Date().toISOString()});}catch(_){}}return json({articles:[],error:"No news available"},502);}catch(error){return json({articles:[],error:String(error?.message||error)},502);}}
export default{async fetch(request){const url=new URL(request.url);if(request.method==="OPTIONS")return new Response(null,{status:204,headers:cors()});if(request.method!=="GET"&&!(request.method==="POST"&&url.pathname==="/trade-analysis"))return json({error:"Read-only API"},405);if(url.pathname==="/health")return health();if(url.pathname==="/public/pride-league"||url.pathname==="/league-data")return prideLeague();if(url.pathname==="/depth-charts")return depthCharts(url);if(url.pathname==="/current-games")return currentGames();if(url.pathname==="/news")return news();if(url.pathname==="/waivers"||url.pathname==="/free-agents")return waivers(url);if(url.pathname==="/best-moves")return bestMoves(url);if(url.pathname==="/trade-analysis")return tradeAnalysis(request);if(url.pathname.startsWith("/auth/")||url.pathname.startsWith("/account/")||url.pathname==="/chat")return json({error:"Authentication has been removed. This production API is read-only."},410);return json({error:"Not found"},404);}};
