const PRIDE_LEAGUE_ID = "astbqxhwmk4b6bg9";
const FANTRAX_GENERAL = "https://www.fantrax.com/fxea/general/";
const ESPN_SCOREBOARD = "https://site.web.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard?limit=100";
const ESPN_HEALTH = "https://cdn.espn.com/core/nfl/scoreboard?xhr=1";
const TEAM_IDS = {ATL:1,BUF:2,CHI:3,CIN:4,CLE:5,DAL:6,DEN:7,DET:8,GB:9,TEN:10,IND:11,KC:12,LV:13,LAR:14,MIA:15,MIN:16,NE:17,NO:18,NYG:19,NYJ:20,PHI:21,ARI:22,PIT:23,LAC:24,SF:25,SEA:26,TB:27,WAS:28,WSH:28,CAR:29,JAX:30,BAL:33,HOU:34};
const YEAR = () => new Date().getUTCFullYear();
const DEPTH_URL = id => `https://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/${YEAR()}/teams/${id}/depthcharts`;
const ROSTER_URL = id => `https://site.api.espn.com/apis/site/v2/sports/football/nfl/teams/${id}/roster`;

function cors(){return {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET,OPTIONS","Access-Control-Allow-Headers":"Accept,Content-Type","Cache-Control":"no-store"};}
function json(body,status=200){return new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json; charset=utf-8",...cors()}});}
function headers(extra={}){return {Accept:"application/json, text/plain, */*","Accept-Language":"en-US,en;q=0.9","User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36",Referer:"https://www.espn.com/",...extra};}
async function fetchJson(url){const r=await fetch(url,{headers:headers(),cf:{cacheTtl:30,cacheEverything:true}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json();}
function clean(v){return String(v||"").replace(/\s+/g," ").trim();}
function teamCode(v){return clean(v).toUpperCase().replace(/[^A-Z]/g,"").replace(/^WSH$/,"WAS").slice(0,4);}
function athleteName(row){return clean(row?.athlete?.displayName||row?.athlete?.fullName||row?.displayName||row?.fullName||row?.name||row?.player?.displayName||row?.player?.fullName);}
function athleteId(value){const t=String(value||"");return t.match(/\/athletes\/(\d+)/)?.[1]||t.match(/^(\d+)$/)?.[1]||null;}
function slotBase(key,position){const raw=clean(key||position?.abbreviation||position?.name).toUpperCase().replace(/[^A-Z0-9]/g,"");const aliases={LEFTWIDERECEIVER:"LWR",RIGHTWIDERECEIVER:"RWR",SLOTWIDERECEIVER:"SWR",SLOTRECEIVER:"SWR",LEFTCORNERBACK:"LCB",RIGHTCORNERBACK:"RCB",NICKELCORNERBACK:"NCB",NICKELBACK:"NCB",FREESAFETY:"FS",STRONGSAFETY:"SS",MIDDLELINEBACKER:"MIKE",WEAKSIDELINEBACKER:"WILL",STRONGSIDELINEBACKER:"SAM",LEFTDEFENSIVEEND:"LDE",RIGHTDEFENSIVEEND:"RDE",NOSETACKLE:"NT"};if(aliases[raw])return aliases[raw];return raw.slice(0,10)||"DEPTH";}
function collectRosterNames(node,map){if(!node)return;if(Array.isArray(node)){node.forEach(x=>collectRosterNames(x,map));return;}if(typeof node!=="object")return;const id=String(node.id||node.athlete?.id||"");const name=athleteName(node)||athleteName(node.athlete);if(id&&name)map.set(id,name);Object.values(node).forEach(v=>collectRosterNames(v,map));}
function parseDepth(depth,team,nameMap){const rows=[],seen=new Set();for(const chart of depth?.items||[]){const formation=clean(chart?.name)||null;for(const [key,group] of Object.entries(chart?.positions||{})){const base=slotBase(key,group?.position);const athletes=Array.isArray(group?.athletes)?group.athletes:Array.isArray(group?.players)?group.players:[];athletes.forEach((row,index)=>{const ref=row?.athlete?.$ref||row?.$ref||row?.athlete?.ref||"";const id=String(row?.athlete?.id||row?.id||athleteId(ref)||"");const name=athleteName(row)||athleteName(row?.athlete)||nameMap.get(id)||"";if(!name)return;const rank=Number(row?.rank??row?.depth??row?.order)||index+1;const slot=`${base}${rank}`;const key2=`${team}|${name.toLowerCase()}|${slot}`;if(seen.has(key2))return;seen.add(key2);rows.push({name,athleteId:id||null,team,slot,baseSlot:base,depth:rank,providerPosition:clean(group?.position?.name||group?.position?.displayName||key)||null,formation});});}}return rows;}
async function oneTeam(team){const id=TEAM_IDS[team];if(!id)return {team,rows:[],error:"Unknown team"};try{const [depth,roster]=await Promise.all([fetchJson(DEPTH_URL(id)),fetchJson(ROSTER_URL(id))]);const names=new Map();collectRosterNames(roster,names);return {team,rows:parseDepth(depth,team,names),error:null};}catch(e){return {team,rows:[],error:String(e?.message||e)};}}
async function depthCharts(url){const requested=[...new Set(String(url.searchParams.get("teams")||"").split(",").map(teamCode).filter(Boolean))].slice(0,32);const teams=requested.length?requested:Object.keys(TEAM_IDS).filter(x=>x!=="WSH");const results=await Promise.all(teams.map(oneTeam));const byTeam={},players=[],errors=[];for(const r of results){byTeam[r.team]=r.rows;players.push(...r.rows);if(r.error)errors.push(`${r.team}: ${r.error}`);}return json({teams:byTeam,players,source:"ESPN NFL depth charts",syncedAt:new Date().toISOString(),season:YEAR(),requestedTeams:teams.length,returnedTeams:Object.keys(byTeam).length,errors});}

async function fantrax(endpoint){const u=new URL(FANTRAX_GENERAL+endpoint);u.searchParams.set("leagueId",PRIDE_LEAGUE_ID);const r=await fetch(u.toString(),{headers:headers({Referer:"https://www.fantrax.com/"}),cf:{cacheTtl:20,cacheEverything:true}});if(!r.ok)throw new Error(`${endpoint} HTTP ${r.status}`);return r.json();}
function normalizeTeam(id,row){const items=Array.isArray(row?.rosterItems)?row.rosterItems:[];return {id,name:row?.teamName||id,players:items.map(item=>{const p=item?.player||item;return {id:String(p?.id||item?.id||""),name:p?.name||p?.playerName||item?.name||"Unknown",position:p?.position||p?.pos||item?.position||"",nflTeam:p?.team||p?.nflTeam||item?.team||"",salary:item?.salary??p?.salary??null,contract:item?.contract??item?.contractInfo??null,rosterSlot:item?.rosterSlot||item?.status||""};})};}
async function prideLeague(){try{const [rosters,info,picks]=await Promise.all([fantrax("getTeamRosters"),fantrax("getLeagueInfo").catch(()=>null),fantrax("getDraftPicks").catch(()=>null)]);const teams=Object.entries(rosters?.rosters||{}).map(([id,row])=>normalizeTeam(id,row));return json({ok:true,leagueId:PRIDE_LEAGUE_ID,leagueName:info?.leagueName||info?.name||"Pride Dynasty",teams,picks:picks?.futureDraftPicks||picks||null,syncedAt:new Date().toISOString(),source:"Fantrax live read-only"});}catch(e){return json({ok:false,error:"Fantrax league sync failed",detail:String(e?.message||e),leagueId:PRIDE_LEAGUE_ID},502);}}

function normalizeGame(event){const c=event?.competitions?.[0]||{},rows=c?.competitors||[];const h=rows.find(x=>x.homeAway==="home")||{},a=rows.find(x=>x.homeAway==="away")||{};const t=x=>({id:x?.team?.id||null,name:x?.team?.displayName||x?.team?.name||null,abbreviation:x?.team?.abbreviation||null,score:x?.score??null});return {id:event?.id||null,date:event?.date||c?.date||null,status:event?.status?.type?.shortDetail||event?.status?.type?.description||"Scheduled",venue:c?.venue?.fullName||null,home:t(h),away:t(a)};}
async function currentGames(){try{const data=await fetchJson(ESPN_SCOREBOARD);const events=data?.events||data?.content?.sbData?.events||[];return json({schedule:events.map(normalizeGame),source:"ESPN NFL scoreboard",syncedAt:new Date().toISOString()});}catch(e){return json({schedule:[],error:String(e?.message||e)},502);}}
async function health(){const checks={worker:true,fantrax:false,espn:false};const errors=[];try{const r=await fetch(FANTRAX_GENERAL+"getPlayerIds?sport=NFL",{headers:headers({Referer:"https://www.fantrax.com/"})});checks.fantrax=r.ok;if(!r.ok)errors.push(`Fantrax HTTP ${r.status}`);}catch(e){errors.push(`Fantrax: ${String(e?.message||e)}`);}try{const r=await fetch(ESPN_HEALTH,{headers:headers()});checks.espn=r.ok;if(!r.ok)errors.push(`ESPN HTTP ${r.status}`);}catch(e){errors.push(`ESPN: ${String(e?.message||e)}`);}return json({ok:checks.worker&&checks.fantrax&&checks.espn,service:"gmslocker-api",version:"3.0.0-public-no-auth",auth:false,leagueId:PRIDE_LEAGUE_ID,checks,errors,checkedAt:new Date().toISOString()});}

export default {async fetch(request){const url=new URL(request.url);if(request.method==="OPTIONS")return new Response(null,{status:204,headers:cors()});if(request.method!=="GET")return json({error:"Read-only API"},405);if(url.pathname==="/health")return health();if(url.pathname==="/public/pride-league"||url.pathname==="/league-data")return prideLeague();if(url.pathname==="/depth-charts")return depthCharts(url);if(url.pathname==="/current-games")return currentGames();if(url.pathname.startsWith("/auth/")||url.pathname.startsWith("/account/")||url.pathname==="/chat"||url.pathname.startsWith("/trade-"))return json({error:"Authentication has been removed. This production API is read-only."},410);return json({error:"Not found"},404);}};
